name: Node CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: muntianus/.github/.github/workflows/reusable-ci-node.yml@main
